# project info
site_name: NDX 产品文档站
site_description: 统一存放了 NDX 团队的调研文档
site_author: ndx.daocloud.io
site_url: http://localhost:8000
repo_url: https://gitlab.daocloud.cn/ndx/product/product-research-document
repo_name: Product Research
edit_uri: ./edit/master/docs

theme:
  name: material
  logo: images/icon.png
  favicon: images/icon.png
  icon:
    repo: fontawesome/brands/git
  font: false
  sticky_navigation: false
  include_homepage_in_sidebar: true
  prev_next_buttons_location: both
  language: zh
  
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
#    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - tabs: true

    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate

    - header.autohide

extra:
  alternate:
    - name: English
      link: en/
      lang: en
    - name: 中文
      link: zh/
      lang: zh
  
  generator: true
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk/mkdocs-material
      name: NDX on GitLab

plugins:
  - mermaid2
  - search
  - tags:
        tags_file: tags.md
  - git-revision-date
  - rss


extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - javascripts/shortcuts.js

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      title: On this page
      toc_depth: 4
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - def_list
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
